### ISSUE TITLE
Uncaught error:  Request body size exceeds 122880

### ISSUE THREAD

**Issue by kevinl95** [auth0/webtask-bundle#15]
When trying to upload a bundle that is 2.6MB in size, I received the following error:
`Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Please report this at: https://github.com/auth0/wt-cli/issues`

I was trying to include GCloud, which is a 55MB module. Is this the potential reason my bundle has exceeded the size allowed? Are we restricted to small modules only?

**Comment by kevinl95** [comment]
Support confirmed there is a 100kb filesize limit.
